#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
#alias ls='ls --color=auto'
LS_COLORS='di=0';export LS_COLORS
PS1='[\u@\h \W]\$ '
neofetch
export VISUAL=vim
export EDITOR="$VISUAL"
